[".zgenom"]
    type = "archive"
    url = "https://github.com/jandamm/zgenom/archive/main.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
